---
title: Bright Pixels
timezone: America/Chicago
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
  - scope:
      path: ''
      type: posts
    values:
      custom_type: link
      subtitle:
      excerpt:
      layout: post
      author: timsmith
      seo_title:
      link_url:
      featured_image:
      is_rss_only:
      review:
        type:
        rating:
        movie:
          letterboxd:
name: Bright Pixels
url: https://brightpixels.blog
description:
  A web-column about comic books, Star Wars, movies, Apple, technology,
  and other geekery.
permalink: '/:year/:month/:title/'
exclude:
  - README.md
  - Gemfile.lock
  - LICENSE
livereload: true
highlighter: rouge
port: 4000
sass:
  sass_dir: assets/stylesheets
  style: compressed
markdown: kramdown
markdown_ext: markdown,mkdown,mkdn,mkd,md,mdown
kramdown:
  input: GFM
plugins:
  - jekyll-typogrify
  - jekyll-include-cache
imgix:
  source: brightpixels.imgix.net
  secure_url_token: yecPTdx6GYCCJd7M
sizes:
  '(min-width: 90em) 1300px, (min-width: 70em) 1000px, (min-width: 50em) 750px,
  (min-width: 31.5em) 500px, 100vw'
srcset:
  - 500
  - 750
  - 1000
  - 1300
webmentions:
  username: brightpixels.blog
  cache_bad_uris_for: 7
  html_proofer: true
  throttle_lookups:
    last_month: daily
    last_year: weekly
    older: every 2 months
  legacy_domains:
    - https://brightlycolored.org
    - http://theboldreport.net
    - https://theboldreport.net
  templates:
    likes: _includes/webmentions/like.html
    reposts: _includes/webmentions/repost.html
    webmentions: _includes/webmentions/webmention.html
